In [2]:
    import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
#data type of an array
arr=np.array([1,2,3,4],dtype=str)


In [6]:
arr1=np.arange(10,40,2)

In [7]:
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
#inserting data in a array
arr1=np.insert(arr1,5,2)

In [9]:
#deleting an array
arr1=np.delete(arr1,5)

In [11]:
arr1

array([10, 12, 14, 16, 18,  2, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
arr1.shape

(15,)

In [11]:
#matrices
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
arr2.shape

(3, 4)

NameError: name 'arr5' is not defined

In [14]:
#
a=[i for i in range(10000000)]

In [15]:
b=[[i for i in range(10000000,100000000)]]

In [16]:
c=[]

In [17]:
a=[i for i in range(10000000)]
b=[i for i in range(10000000,100000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

1.1517939567565918


In [21]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
arr3=arr1+arr2
print(time.time()-start)

0.02115488052368164


In [22]:
6.2/0.47


13.191489361702128

In [46]:
mat=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [47]:
print(mat)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [53]:
mat[1,1,1]

14

In [45]:
for i in range(4):
    print(mat[i,1])

2
6
10
14


In [58]:
dn=np.array([1,1,1],np.array==14)

TypeError: Cannot interpret 'False' as a data type